apiVersion: v1
kind: Secret
metadata:
  name: argocd-secret
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-secret
    app.kubernetes.io/part-of: argocd
type: Opaque
data:
  admin.password: xxx
  admin.passwordMtime: xxx
  tls.crt: xxx
  tls.key: xxx
  webhook.github.secret: it's a secret !