apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-tls-certs-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  harbor.gslab.lan: |
    -----BEGIN CERTIFICATE-----
    certif...
    -----END CERTIFICATE-----